language: python

# Run on all major versions of python since 2.7
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"   # Nightly build

# Install dependencies
install:
  - pip install -r requirements.txt

# Command to run tests
script:
  - pytest